INSERT INTO users (name, email, phone, userName, password, profileImage, location, createdAt, updatedAt) 
VALUES ("Edward", "Edward@mail.com", "9498574135", "Edward Wholesale", "eddie", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMk8J6ruoonekGCvhsuFwBJJDCjKgN2YJEZ5RgQykuOO-YTxR8", "Tustin, CA", "2017-09-27 03:14:48", "2017-09-27 03:14:48"),
("Frederick", "Frederick@mail.com", "6265249478", "Fredo Store", "jalalo", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrurDVq-5BHVA_w2RdXy_gmZ7CBzKBbRVoLPvvusk-dsDLx4B-uQ", "Santa Ana, CA", "2017-09-27 03:14:48", "2017-09-27 03:14:48"),
("Robby", "Robby@mail.com", "6265843125", "NTZ for Less", "Robbie", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQplvpkIEDlqhp8SVJU5cJuYeHR2bB24sCE5ynJLlDXGg1wVTaW3w", "Irvine, CA", "2017-09-27 03:14:48", "2017-09-27 03:14:48"),
("Horazio", "Horazio@mail.com", "9192543185", "Zaballeroh", "mosesy", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtjdiQ0g4UOvjro_l4FHDyjW3x8WJI1rBfb6V5ODjh9kkNlozW", "San Diego, CA", "2017-09-27 03:14:48", "2017-09-27 03:14:48"),
("Angelo", "Angela@mail.com", "9095243161", "Angel Collection", "Angelo", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOP6IY__LfooP_rjODFEU7ohMuajV3nFXyoKw1U1nwjqvvOAyHUQ", "Orange, CA", "2017-09-27 03:14:48", "2017-09-27 03:14:48");


INSERT INTO products (productName, category, description, price, imageURL, createdAt, updatedAt, UserId) 
VALUES ("Harry Potter and the Deathly Hallows (Book 7)", "Books", "Readers beware. The brilliant, breathtaking conclusion to J.K. Rowling's spellbinding series is not for the faint of heart--such revelations, battles, and betrayals await in Harry Potter and the Deathly Hallows that no fan will make it to the end unscathed. Luckily, Rowling has prepped loyal readers for the end of her series by doling out increasingly dark and dangerous tales of magic and mystery, shot through with lessons about honor and contempt, love and loss, and right and wrong. Fear not, you will find no spoilers in our review--to tell the plot would ruin the journey, and Harry Potter and the Deathly Hallows is an odyssey the likes of which Rowling's fans have not yet seen, and are not likely to forget. But we would be remiss if we did not offer one small suggestion before you embark on your final adventure with Harry--bring plenty of tissues.", "20.20", "hpbook.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","1"),
("Baby Panda Stuffed Animal Plush Toy", "Toys", "Baby Panda: (American English Version) Baby Panda is the baby of the group. Everyone loves her and wants to look after and play with her! All Baby Panda wants to do is play, play and play some more! You'll often see her down at the park, or simply rolling down hills! Includes 4 nursery rhymes: ABC Song/Alphabet Song* Row, Row, Row Your Boat Head, Shoulders, All Baby Panda wants to do is play, play and play some more! You'll often see her down at the park, or simply rolling down hills! Knees and Toes Humpty Dumpty", "11.20", "panda.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","2"),
("WAR", "Movies", "War film is a film genre concerned with warfare, typically about naval, air, or land battles, with combat scenes central to the drama. It has been strongly associated with the 20th century.[1][2] The fateful nature of battle scenes means that war films often end with them. Themes explored include combat, survival and escape, sacrifice, the futility and inhumanity of battle, the effects of war on society, and the moral and human issues raised by war. The stories told may be fiction, historical drama, or biographical. Critics have noted similarities between the Western and the war film.", "1.20", "war.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48", "2"),
("James Bond - From Russia With Love, 1963", "Movies", "When MI6 gets a chance to get their hands on a Lektor decoder, Bond is sent to Turkey to seduce the beautiful Tatiana, and bring back the machine. With the help of Kerim Bey, Bond escapes on the Orient Express, but might not make it off alive. The complete list of official James Bond films, made by EON Productions. Beginning with Sean Connery, and going through George Lazenby, Roger Moore, Timothy Dalton, Pierce Brosnan and Daniel Craig. Have you ever wondered how many James Bond movies there are? The newest film, Spectre, was released in October 2015.", "1.11", "james.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48", "3"),
("Eloquent JavaScript, 2nd Edition", "Books", "Eloquent JavaScript by Marijn Haverbeke is a book is aimed at ambitious beginners. The author assumes no prior JavaScript knowledge on the part of the reader and does a great job of introducing them to the language in an informative, yet entertaining way. One of my favorite things about this book is that it doesn’t just focus on the mechanics of the language, rather it teaches the fundamental concepts of programming and computer science to boot.
The book is split into three parts — the first concentrates on the language itself, the second concerns using JavaScript in the browser and the third (and smallest) part is devoted to Node.js. It also contains exercises and project chapters (in my opinion a great way of reinforcing the concepts learned). These see readers build such things as an artificial life simulation and their own programming language (I did say ambitious).", "13.13", "javascript.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48", "3"),
("Dell - Inspiron Desktop", "Computers", "Succeed in online adventures with this Dell Inspiron gaming desktop. Its 16GB of RAM and AMD Ryzen 7 processor have the power to run up-to-date software, and its AMD Radeon RX 580 graphics card ensures realistic image rendering.Windows 10 Home software, and its powerful Intel Core i5 processor with 8GB of DDR4 RAM keeps programs running smoothly. This Samsung laptop PC has a 1TB hard drive, providing plenty of file storage space. This Dell Inspiron gaming desktop has a 1TB hard drive to hold large program files.", "300.30", "laptop9.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","1"), 
("Dell XPS 27 inch looks like new", "Computers", "Select this Dell XPS computer for versatile power at work or play. Its Intel Core i7 processor and 16GB of DDR4 RAM keep your program operations running seamlessly. It also contains exercises and project chapters (in my opinion a great way of reinforcing the concepts learned). These see readers build such things as an artificial life simulation and their own programming language. This Dell XPS computer has a 2TB hard drive to meet your large-file storage needs, providing room for plenty of photographs or video games.", "1021.12", "laptop1.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","1"), 
("Touch-Screen Laptop - Intel Core i5 by Samsung", "Computers", "Samsung 5 Laptop: Experience the versatility of this 15.6-inch Samsung laptop PC. It can be used as a tablet when needed with its preinstalled Windows 10 Home software, and its powerful Intel Core i5 processor with 8GB of DDR4 RAM keeps programs running smoothly. This Samsung laptop PC has a 1TB hard drive, providing plenty of file storage space.", "620.20", "laptop5.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","2"), 
("The best used S7 Samsung phone you ever see ", "Smartphones", "Use this unlocked Samsung Galaxy S7 Edge phone to stay in touch with friends and family. Its defense-grade KNOX platform provides enhanced security, and it's IP6s water-resistant for protection against spills. A 12-megapixel camera captures quality pictures, and the 3600 mAh battery provides fast charging. Store plenty of information with the expandable 200GB memory of this Samsung Galaxy phone.", "655.55", "iphone1", "2017-09-27 03:14:48", "2017-09-27 03:14:48","2"), 
("LED - 2160p - Smart - 4K Ultra HD Samsung TV", "TVs", "Bring movies and television to life with this 50-inch Samsung smart TV. It has 4K resolution for a clear, sharp picture with bright, true-to-life colors. This Samsung smart TV has an intuitive toolbar for quick access to streaming services, apps and live TV all in one place.  If no modifications are listed, the item is unopened and untested. Defects & blemishes are significantly reduced by our in-depth inspection & testing.", "800.80", "tv.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","2"), 
("Mint 2017 Lenovo ThinkPad", "Computers", " ThinkPad E560 Laptop | 15-inch Business Laptop: OUTSTANDING VALUE AND PERFORMANCE. Revolutionary performance, exceptional mobility and outstanding features for business. That describes the slim, light ThinkPad E560 (15.6 inch) notebooks. With latest generation of Intel Skylake processor, extensive memory and storage options, enhanced connectivity. Ready for business at a surprisingly affordable price!", "555.55", " laptop4.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","3"), 
("Lenovo ThinkPad Edge E560", "Computers", "Intel 6th Gen Core i5-6200U (Dual Core, 2.3 / 2.8GHz, 3MB, 1600MHz). 16GB Upgraded DDR3 Memory (maximum memory capacity 16 GB), 512GB Solid State Drve, SSD DVD Reader and Writer. 15.6 Inch. Anti-glare HD (1366x768) with Intel HD graphics 520 and 720P Webcam Windows 7 Professional Installed with License Upgradable to Windows 10 Professional", "211.12", "laptop6.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","3"), 
("Acer Chromebook R 13 Convertible, 13.3-inch Full HD Touch", "Computers", "Warranty, Labor:Trivalley Electronics sells computers with upgraded configurations. If the computer has modifications (listed above), then the manufacturer box is opened for it to be tested and inspected and to install the upgrades to achieve the specifications as advertised. If no modifications are listed, the item is unopened and untested. Defects & blemishes are significantly reduced by our in-depth inspection & testing. Trivalley Electronics is the first point of contact for all warranty concerns on upgraded / custom computers.", "333.33", "laptop7.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","3"), 
("17 Inch Toshiba Laptop for sale", "Computers", "This Certified Refurbished product is tested and certified to look and work like new. The refurbishing process includes functionality testing, basic cleaning, inspection, and repackaging. The product ships with all relevant accessories, a minimum 90-day warranty, and may arrive in a generic box. Only select sellers who maintain a high-performance bar may offer Certified Refurbished products on Amazon.com", "369.69", "laptop10.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","3"), 
("Refurbished Latitude E6430 Premium", "Computers", "Dell Latitude E6430 Premium 14 Inch Business Laptop Computer, Intel Dual Core i7-3520M 2.9Ghz Processor, 8GB RAM, 128GB SSD, DVD, HDMI, Windows 10 Professional (Certified Refurbished). With innovations that deliver higher contrast, dual-domain pixels for more accurate color at wider viewing angles, and an improved polarizer, these are the thinnest, most advanced Multi-Touch displays. Its incredible power is enhanced by an M8 motion coprocessor that efficiently measures your activity from advanced sensors, including a new barometer. So you can do more, for longer periods of time, with better performance and battery life.", "179.88", "laptop8.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","1"),
("BRAND NEW eMachine E222 for sale", "Computers", "Get reliable performance from the Intel Core i7-3520M 2.9GHz dual-core processor 14 inch Anti-Glare HD LED-backlit display with 1366 x 768 resolution showcases movies and games in stunning clarity; 8GB DDR3 memory - For multitasking power; supports up to 16GB; 128GB Solid State Drive has plenty of space to store your digital albums, music library and rich media files Enhanced viewing with the integrated Intel HD 4000 graphics; Windows 10 Professional was designed for on-the-go working professionals.", "777.77", "laptop7.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","4"),
("Dell Latitude E6420 Laptop WEBCAM", "Computers", "This item Dell Latitude E6430 Premium 14 Inch Business Laptop Computer, Intel Dual Core i7-3520M 2.9Ghz Processor, 8GB RAM, 128GB SSD, DVD, HDMI, Windows 10 Professional (Certified Refurbished)", "456.40", "laptop10.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","4"), 
("LIKE NEW Rose Gold Space Gray iPhone 6S 128GB Factory UNLOCKED TMobile Straight Talk", "Smartphones", "NEW Space Gray or Rose Gold iPhone 6S 64GB or 128 GB Forever Factory Unlocked on new software v. 9 for All SIM Cards Worldwide & USA(tested with Straight Talk, Verizon, AT&T, and TMobile SIMs; but it works with all SIMs). 1-Year Warranty Included. Attention Buyers: These iPhones are forever unlocked and support iTunes updates.  You should choose the carrier that you plan to use though, and we can send a free SIM card.", "200.10", "laptop4.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","4"), 
("Apple iPhone 6 (Factory Unlocked) AT&T Verizon T-Mobile Gray S Silver", "Smartphones", "3G Data Capable, 4G Data Capable, Accelerometer, Bluetooth Enabled, Fingerprint Sensor, GPS, Internet Browser, Near Field Communication, Speakerphone, Touchscreen, TTY Compatible, Voice-Activated Dialing, Wi-Fi Capable. With innovations that deliver higher contrast, dual-domain pixels for more accurate color at wider viewing angles, and an improved polarizer, these are the thinnest, most advanced Multi-Touch displays. Its incredible power is enhanced by an M8 motion coprocessor that efficiently measures your activity from advanced sensors, including a new barometer. So you can do more, for longer periods of time, with better performance and battery life.", "159.59", "iphone2.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","4"), ("Apple iPhone 7 32GB GSM Unlocked Smartphone", "Smartphones", "iPhone 7 is in Manufacturer Refurbished condition. The unit will have minor scuffs and/or scratches on body or screen. Device comes packaged in an aftermarket box with an aftermarket charger! This phone is compatible with AT&T, T-Mobile, Simple Mobile, Ultra Mobile, etc. It lets you shoot stunning 1080p HD video at 60 fps, capture more dramatic slo-mo video, and for the first time, create time-lapse videos. Continuous autofocus provides constant focus as you capture your footage. And cinematic video stabilization keeps your shots steady, even when you're not. Will NOT work on any CDMA Carriers (Sprint, Verizon, PagePlus, Boost Mobile etc.)", "333.33", "iphone4.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","5"), 
("iPhone 7 in Manufacturer Refurbished Condition", "Smartphones", "This is an iPhone 7 in Manufacturer Refurbished Condition. Item is fully functional. With a clean ESN. This item will come with minor scratches on the screen and/or body of the unit. Scratches can easily be covered with a case or screen protector. Device Is Unlocked For All GSM Carriers", "355.00", "iphone0.jpg", "2017-09-27 03:14:48", "2017-09-27 03:14:48","5")